[build]
  publish = "."
  command = "echo 'No build needed - static HTML files'"

[[redirects]]
  from = "/"
  to = "/beer-dash_en.html"
  status = 200

[[redirects]]
  from = "/ja"
  to = "/beer-dash.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"